import React, { useState } from 'react';
import CodeEditor from './components/CodeEditor';
import ReviewOutput from './components/ReviewOutput';
import ScoringDashboard from './components/ScoringDashboard';
import ReviewHistory from './components/ReviewHistory';
import CorrectedCode from './components/CorrectedCode';
import { reviewCode, detectLanguage } from './services/codeReviewService';
import { useReviewHistory } from './components/ReviewHistory';
import './App.css';

function App() {
  const [code, setCode] = useState('// Paste your code here\nfunction example() {\n  return "Hello World";\n}');
  const [language, setLanguage] = useState('javascript');
  const [review, setReview] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const { saveReview } = useReviewHistory();
  const [currentReviewId, setCurrentReviewId] = useState(null);

  const handleReview = async () => {
    if (!code.trim()) {
      setError('Please paste some code first');
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const detectedLang = language || detectLanguage(code);
      const reviewResult = await reviewCode(code, detectedLang);
      setReview(reviewResult);
      saveReview(code, detectedLang, reviewResult);
    } catch (err) {
      setError(err.message || 'Error reviewing code. Please check your API key and try again.');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleFileUpload = (filename, content) => {
    const ext = filename.split('.').pop().toLowerCase();
    const langMap = {
      js: 'javascript',
      jsx: 'javascript',
      ts: 'typescript',
      tsx: 'typescript',
      py: 'python',
      java: 'java',
      cpp: 'cpp',
      cc: 'cpp',
      cxx: 'cpp',
      cs: 'csharp',
      go: 'go',
      php: 'php',
      rb: 'ruby',
      rs: 'rust',
      swift: 'swift',
      kt: 'kotlin',
      kts: 'kotlin',
      sql: 'sql',
      html: 'html',
      htm: 'html',
      css: 'css',
      json: 'json',
      yaml: 'yaml',
      yml: 'yaml',
      md: 'markdown',
      sh: 'bash',
      bash: 'bash',
      ps1: 'powershell',
    };
    if (langMap[ext]) {
      setLanguage(langMap[ext]);
    }
  };

  const handleLoadReview = (review) => {
    setCode(review.code);
    setLanguage(review.language);
    setReview(review.review);
    setCurrentReviewId(review.id);
  };

  const handleExport = () => {
    if (!review) return;

    let markdown = `# Code Review Report\n\n`;
    markdown += `**Overall Score:** ${review.overallScore}/100\n\n`;
    markdown += `**Summary:** ${review.summary}\n\n`;

    markdown += `## Issue Summary\n`;
    markdown += `- Critical: ${review.issues.filter((i) => i.severity === 'Critical').length}\n`;
    markdown += `- Warning: ${review.issues.filter((i) => i.severity === 'Warning').length}\n`;
    markdown += `- Info: ${review.issues.filter((i) => i.severity === 'Info').length}\n\n`;

    const categories = ['Bugs', 'Quality', 'Performance', 'Security', 'BestPractices'];
    categories.forEach((category) => {
      const issues = review.issues.filter((i) => i.category === category);
      if (issues.length > 0) {
        markdown += `## ${category}\n\n`;
        issues.forEach((issue) => {
          markdown += `### [${issue.severity}] ${issue.title} (Line ${issue.lineNumber})\n`;
          markdown += `${issue.description}\n`;
          if (issue.suggestedFix) {
            markdown += `\`\`\`\n${issue.suggestedFix}\n\`\`\`\n`;
          }
          markdown += `\n`;
        });
      }
    });

    markdown += `---\n*Generated by AI Code Reviewer*\n`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `code-review-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  const handleCopy = () => {
    if (!review) return;

    let text = `Code Review Report\n\n`;
    text += `Overall Score: ${review.overallScore}/100\n`;
    text += `Summary: ${review.summary}\n\n`;

    review.issues.forEach((issue) => {
      text += `[${issue.severity}] ${issue.title} (Line ${issue.lineNumber})\n`;
      text += `${issue.description}\n`;
      if (issue.suggestedFix) {
        text += `Fix: ${issue.suggestedFix}\n`;
      }
      text += `\n`;
    });

    navigator.clipboard.writeText(text).then(() => {
      alert('Review copied to clipboard!');
    });
  };

  const handleCopyCorrectedCode = () => {
    alert('✅ Corrected code copied to clipboard!');
  };

  const handleApplyToEditor = (correctedCode) => {
    setCode(correctedCode);
    alert('✅ Corrected code applied to editor!');
  };

  return (
    <div className="app-shell p-4 sm:p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <header className="app-topbar mb-6 rounded-xl px-6 py-5">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h1 className="app-main-title text-3xl sm:text-4xl font-bold mb-1">🤖 AI Code Reviewer</h1>
              <p className="text-slate-300">Get intelligent code review feedback powered by AI</p>
            </div>
            <div className="app-status-pill inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm font-medium">
              <span className="h-2 w-2 rounded-full bg-emerald-400" />
              Analysis Engine Online
            </div>
          </div>
        </header>

        <div className="mb-6">
          <p className="text-slate-400 text-sm">
            Professional review workspace with a modern Cursor-inspired dark dashboard theme.
          </p>
        </div>

        {/* Error Message */}
        {error && (
          <div className="mb-4 p-4 bg-red-900 border border-red-600 rounded-lg text-red-100">
            <p className="font-semibold">❌ Error:</p>
            <p className="text-sm mt-1">{error}</p>
          </div>
        )}

        {/* Main Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 lg:min-h-[calc(100vh-200px)]">
          {/* Left: Code Editor + History */}
          <div className="lg:col-span-2 flex flex-col gap-4 min-h-0">
            <div className="min-h-[320px] lg:flex-1 lg:min-h-0">
              <CodeEditor
                code={code}
                setCode={setCode}
                language={language}
                setLanguage={setLanguage}
                onReview={handleReview}
                isLoading={isLoading}
                onFileUpload={handleFileUpload}
              />
            </div>
            <div className="min-h-[140px] max-h-[320px] overflow-hidden">
              <ReviewHistory onLoadReview={handleLoadReview} currentReview={currentReviewId} />
            </div>
          </div>

          {/* Right: Review Results + Dashboard */}
          <div className="flex flex-col gap-4 min-h-0">
            <div className="min-h-[280px] lg:flex-1 lg:min-h-0">
              <ReviewOutput review={review} onExport={handleExport} onCopy={handleCopy} />
            </div>
            <div className="min-h-[260px] lg:h-[360px] overflow-hidden">
              <ScoringDashboard review={review} />
            </div>
          </div>
        </div>

        {/* Corrected Code Section */}
        {review && review.correctedCode && (
          <div className="mt-6">
            <CorrectedCode
              correctedCode={review.correctedCode}
              review={review}
              language={language}
              onApplyToEditor={handleApplyToEditor}
              onCopy={handleCopyCorrectedCode}
            />
          </div>
        )}

        {/* Footer */}
        <footer className="app-footer mt-6 rounded-xl px-6 py-4">
          <div className="flex flex-col gap-2 text-sm sm:flex-row sm:items-center sm:justify-between">
            <p>AI Code Reviewer • Built for fast, high-quality code audits.</p>
            <p className="text-slate-400">Secure • Performant • Maintainable</p>
          </div>
        </footer>
      </div>
    </div>
  );
}

export default App;